version: '3.1'

services:
  mongo:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
